version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chat-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w6l37bz19tfv"
s3_prefix = "chat-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"simplechat_connections\""
